{
  "hash": "887a4c787c0ed9fceab1f0329ce2f205",
  "result": {
    "engine": "knitr",
    "markdown": "# Analysis: Fixed Effects and the Main Result {#sec-walker-analysis}\n\n\n\nData processing is over. You have one clean row for every school-year, and you have already looked at the raw means. Now we get to ask the question that motivated all of that work: did the gap in women's share of applicants change differently for schools in states where abortion would be banned?\n\nThe temptation is to jump straight to a regression and trust the coefficient. Resist that. First look at what a very simple model captures. Then make the comparison increasingly more like the one we actually want. That way, fixed effects are not a magic incantation at the end of a long formula. They are a response to a problem you can see in the data.\n\n::: {.callout-note appearance=\"minimal\" title=\"Coding Learning Objectives\"}\n- `feols()`\n- `i()`\n- institution and year fixed effects\n- `summary()` and `iplot()`\n:::\n\n## Start with the Cross-School Difference\n\nThere are 515 school-years in this cleaned sample: 103 schools, observed in each of the five years from 2018 through 2022. In this project, `repeal == 1` marks schools in states classified as banned (the ban, or treated, group); `repeal == 0` marks the comparison group. It is a time-invariant group label here: every school stays in the same group for all five years. That last part matters quite a bit.\n\nStart with the bluntest possible model:\n\n$$\n\\text{wshare}_{ijt}\n= \\beta_0 + \\beta_1\\,\\text{repeal}_{j} + \\varepsilon_{ijt}.\n$$\n\nHere, $\\text{wshare}_{ijt}$ is the women's share of applicants at school $i$, in state $j$, in year $t$. The variable $\\text{repeal}_{j}$ is the group's 0-or-1 label. It has no $i$ or $t$ subscript because a school stays in the same group in every year.\n\nAs in the introduction, let's do something we really shouldn't: take a derivative of an indicator variable. It is not technically correct because $\\text{repeal}_j$ can only be 0 or 1. But the intuition comes through, and that is what matters here.\n\n$$\n\\frac{\\partial \\text{wshare}_{ijt}}\n{\\partial \\text{repeal}_j}\n= \\beta_1.\n$$\n\nRead that derivative as flipping the group label from 0 to 1, not as making an infinitesimal change. In this simple model, $\\beta_1$ is the ban-minus-control predicted difference.\n\nThe exact discrete version says the same thing:\n\n$$\n\\text{wshare}(\\text{repeal}=1)\n- \\text{wshare}(\\text{repeal}=0)\n= \\beta_1.\n$$\n\nSo $\\beta_0$ is the average women's share in the comparison group, and $\\beta_1$ is the pooled ban-minus-control difference across all five years. It is a descriptive group difference, not yet a policy effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbetween_model <- feols(\n  wshare ~ repeal,\n  cluster = ~STABBR,\n  data = df\n)\n\nsummary(between_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wshare\nObservations: 515\nStandard-errors: Clustered (STABBR) \n            Estimate Std. Error  t value  Pr(>|t|)    \n(Intercept) 0.522311   0.009924 52.63285 < 2.2e-16 ***\nrepeal      0.032744   0.013688  2.39218  0.023216 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.080417   Adj. R2: 0.027682\n```\n\n\n:::\n:::\n\n\nThis model has no fixed effects, no year controls, and no claim to be an event study. It pools all five years together and asks whether a school in the ban group has a different women's applicant share than a school in the comparison group.\n\nThe `repeal` coefficient is about 3.3 percentage points. That is a real descriptive fact about this sample: the average women's share is higher at the ban-state schools. It is **not** evidence that anticipated *Dobbs* caused anything. The pooled coefficient mixes years together and also bundles the group label with every long-running difference between its schools and the comparison schools. They could have different academic programs, student populations, regional applicant pools, or a hundred other persistent differences.\n\nThis is the ordinary least squares problem in its most visible form. A cross-school comparison bundles together a policy category and every long-running difference between the schools in that category.\n\n## See the Raw Event-Study Difference\n\nThe research question is not really about the overall level difference. It is about whether the *gap* between the two groups changes. You already calculated that table at the end of data processing. Build it again, this time keeping the difference-in-difference calculation in view.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_gaps <- df |>\n  group_by(repeal, year) |>\n  summarize(wshare = mean(wshare), .groups = \"drop\") |>\n  mutate(group = if_else(repeal == 1, \"ban\", \"control\")) |>\n  select(year, group, wshare) |>\n  pivot_wider(names_from = group, values_from = wshare) |>\n  mutate(\n    gap = ban - control,\n    relative_to_2021 = gap - gap[year == 2021]\n  )\n\nraw_gaps\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n   year control   ban    gap relative_to_2021\n  <dbl>   <dbl> <dbl>  <dbl>            <dbl>\n1  2018   0.516 0.550 0.0339         0.000542\n2  2019   0.517 0.553 0.0366         0.00326 \n3  2020   0.518 0.552 0.0337         0.000292\n4  2021   0.531 0.564 0.0334         0       \n5  2022   0.530 0.556 0.0261        -0.00722 \n```\n\n\n:::\n:::\n\n\nIn 2021, the ban-minus-control gap is 0.033. In 2022 it is 0.026. The difference-in-difference is -0.007, or -0.7 percentage points. The negative sign means the ban-minus-control gap narrowed by about 0.7 percentage points.\n\nWe can put those same group-year comparisons into a regression. This still has no institution fixed effects. It just writes every part of the difference-in-difference comparison explicitly:\n\n$$\n\\begin{aligned}\n\\text{wshare}_{ijt} ={}&\n\\beta_0 + \\beta_1\\,\\text{repeal}_j \\\\\n&+ \\sum_{\\ell \\ne 2021}\n\\gamma_\\ell \\mathbb{1}(t = \\ell) \\\\\n&+ \\sum_{\\ell \\ne 2021}\n\\delta_\\ell \\left[\n\\text{repeal}_j \\times \\mathbb{1}(t = \\ell)\n\\right] + \\varepsilon_{ijt}.\n\\end{aligned}\n$$\n\nHere, $\\beta_1$ is the 2021 ban-minus-control gap, the $\\gamma_\\ell$ terms are the comparison group's shifts from 2021, and the $\\delta_\\ell$ terms are the event-study difference-in-difference estimates. Leaving 2021 out of both sums makes it the reference year.\n\nUse the same informal derivative trick:\n\n$$\n\\frac{\\partial \\text{wshare}_{ijt}}\n{\\partial \\text{repeal}_j}\n= \\beta_1 +\n\\sum_{\\ell \\ne 2021}\n\\delta_\\ell \\mathbb{1}(t = \\ell).\n$$\n\nIn 2022, the 2022 indicator equals 1 and the others equal 0, so the group difference is $\\beta_1 + \\delta_{2022}$. That makes $\\delta_{2022}$ the change in the group difference relative to 2021—the event-study estimate we care about.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_event_study <- feols(\n  wshare ~ repeal +\n    i(year, ref = 2021) +\n    i(year, repeal, ref = 2021),\n  cluster = ~STABBR,\n  data = df\n)\n\nsummary(raw_event_study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wshare\nObservations: 515\nStandard-errors: Clustered (STABBR) \n                   Estimate Std. Error   t value   Pr(>|t|)    \n(Intercept)        0.530710   0.009441 56.215779  < 2.2e-16 ***\nrepeal             0.033371   0.013330  2.503414 0.01797241 *  \nyear::2018        -0.014538   0.004133 -3.517315 0.00141040 ** \nyear::2019        -0.014100   0.003960 -3.560537 0.00125702 ** \nyear::2020        -0.012849   0.003536 -3.633640 0.00103364 ** \nyear::2022        -0.000508   0.000917 -0.554393 0.58341981    \nyear::2018:repeal  0.000542   0.005749  0.094352 0.92545711    \nyear::2019:repeal  0.003257   0.004440  0.733645 0.46886016    \nyear::2020:repeal  0.000292   0.004016  0.072758 0.94248168    \nyear::2022:repeal -0.007223   0.001824 -3.959312 0.00042697 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.08017   Adj. R2: 0.018349\n```\n\n\n:::\n:::\n\n\nThere is a lot packed into that formula, so take it slowly.\n\n- `repeal` is the ban-control difference in the reference year, 2021.\n- `i(year, ref = 2021)` makes a dummy for each non-2021 year. Those terms describe how the control group changes relative to 2021.\n- `i(year, repeal, ref = 2021)` makes the interactions we care about. Each one is the extra change for ban-state schools in that year, relative to the 2021 gap.\n\nThe last set of coefficients are the event-study estimates. Because this is a balanced panel and the model has a group indicator, year indicators, and their interactions, its point estimates are exactly the raw relative-to-2021 gaps in the table above.\n\nAdding school fixed effects changes the comparison mechanically: the raw difference-in-difference compares group-year averages, while the fixed-effect model first removes each school's own usual level and then estimates the event terms from the remaining within-school movement. In this particular balanced data set, with a group label that never changes and a separate interaction for every year, the two models happen to have the same event-study point estimates. That is expected, not evidence that fixed effects did nothing. They make the identifying comparison explicit; in a panel where schools enter, leave, or change composition, the estimates can move. Fixed effects do not, by themselves, solve attrition or every other design problem.\n\nA small vocabulary point: the year indicators in this model do the same mathematical job as year fixed effects. We wrote them out as ordinary right-hand-side terms because there are only five years and it lets you see the moving parts. In a moment, `| year` will absorb them more compactly.\n\nBut this version still treats, say, the University of Florida and Florida State University as interchangeable observations from the same treated group. They are not. Their women's applicant shares have different normal levels, even though both schools are in Florida. That is where institution fixed effects enter.\n\n## What De-meaning Actually Does\n\nFixed effects are often described as \"controlling for a bunch of stuff.\" That is technically true and not very helpful. A more useful description is that fixed effects compare a school to itself.\n\nTake the University of Florida. Its own average women's applicant share in this five-year sample is 0.572. In 2018, its share was 0.577. The school-level de-meaned value is therefore:\n\n$$\n0.577 - 0.572 =\n0.005.\n$$\n\nIn plain English: University of Florida's 2018 share was about half a percentage point above **its own** usual share. We are no longer comparing it to a school in California, New Jersey, or even across town. We are asking whether it was above or below its own normal level.\n\nHere are all five University of Florida observations, with the arithmetic exposed. The `.by = UNITID` line asks `dplyr` to calculate a separate mean within each school; `.by = year` does the same within each calendar year. It is a compact alternative to grouping, calculating, and ungrouping by hand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_demeaned <- df |>\n  mutate(school_mean = mean(wshare), .by = UNITID) |>\n  mutate(year_mean = mean(wshare), .by = year) |>\n  mutate(\n    grand_mean = mean(wshare),\n    school_demeaned = wshare - school_mean,\n    two_way_demeaned = wshare - school_mean - year_mean + grand_mean\n  )\n\ndf_demeaned |>\n  filter(UNITID == 134130) |>\n  select(year, wshare, school_mean, year_mean, grand_mean,\n         school_demeaned, two_way_demeaned) |>\n  mutate(across(-year, ~ round(.x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n   year wshare school_mean year_mean grand_mean school_demeaned two_way_demeaned\n  <dbl>  <dbl>       <dbl>     <dbl>      <dbl>           <dbl>            <dbl>\n1  2018  0.577       0.572     0.524       0.53           0.005            0.011\n2  2019  0.573       0.572     0.526       0.53           0.002            0.006\n3  2020  0.57        0.572     0.526       0.53          -0.001            0.003\n4  2021  0.576       0.572     0.539       0.53           0.004           -0.004\n5  2022  0.562       0.572     0.537       0.53          -0.01            -0.016\n```\n\n\n:::\n:::\n\n\nThe table gives the arithmetic, but a picture makes the first subtraction easier to see. The dashed line below is University of Florida's five-year average. Each vertical segment is the distance from an observed year to that line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nuf_demeaning_plot <- df_demeaned |>\n  filter(UNITID == 134130) |>\n  mutate(\n    deviation_direction = if_else(\n      school_demeaned >= 0,\n      \"Above the mean\",\n      \"Below the mean\"\n    ),\n    deviation_label = paste0(\n      if_else(school_demeaned >= 0, \"+\", \"\"),\n      formatC(100 * school_demeaned, format = \"f\", digits = 1),\n      \" pp\"\n    ),\n    label_vjust = if_else(school_demeaned >= 0, -0.7, 1.4)\n  )\n\nuf_y_limits <- range(c(\n  uf_demeaning_plot$wshare,\n  uf_demeaning_plot$school_mean\n))\nuf_y_padding <- diff(uf_y_limits) * .22\n\nggplot(uf_demeaning_plot, aes(x = year, y = wshare)) +\n  geom_hline(\n    yintercept = uf_school_mean,\n    linetype = \"dashed\",\n    colour = \"grey35\",\n    linewidth = .55\n  ) +\n  geom_line(aes(group = 1), colour = \"grey55\", linewidth = .55) +\n  geom_segment(\n    aes(\n      xend = year,\n      y = school_mean,\n      yend = wshare,\n      colour = deviation_direction\n    ),\n    linewidth = .95\n  ) +\n  geom_point(size = 2.5, colour = \"#1F4E79\") +\n  geom_text(\n    aes(label = deviation_label, vjust = label_vjust),\n    size = 3.4,\n    colour = \"grey20\"\n  ) +\n  annotate(\n    \"text\",\n    x = max(uf_demeaning_plot$year) + .18,\n    y = uf_school_mean,\n    label = \"five-year mean\",\n    hjust = 0,\n    vjust = -0.7,\n    size = 3.2,\n    colour = \"grey25\"\n  ) +\n  scale_colour_manual(\n    values = c(\n      \"Above the mean\" = \"#1F4E79\",\n      \"Below the mean\" = \"#B64E31\"\n    ),\n    guide = \"none\"\n  ) +\n  scale_x_continuous(\n    breaks = sort(unique(uf_demeaning_plot$year)),\n    expand = expansion(mult = c(.04, .19))\n  ) +\n  scale_y_continuous(labels = scales::label_percent(accuracy = .1)) +\n  coord_cartesian(\n    ylim = uf_y_limits + c(-uf_y_padding, uf_y_padding),\n    clip = \"off\"\n  ) +\n  labs(\n    x = NULL,\n    y = \"Women's share of applicants\",\n    caption = \"Above the mean: positive de-meaned value. Below the mean: negative de-meaned value.\"\n  ) +\n  theme_minimal(base_size = 12, base_family = \"Helvetica\") +\n  theme(\n    panel.border = element_rect(colour = \"black\", fill = NA, linewidth = .65),\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor = element_blank(),\n    plot.caption = element_text(hjust = 0),\n    plot.margin = margin(t = 14, r = 52, b = 14, l = 14)\n  )\n```\n\n::: {.cell-output-display}\n![University of Florida before school de-meaning. Each vertical segment is the observed share minus the school's five-year average.](walker-analysis_files/figure-html/school-demeaning-plot-1.png){fig-alt='A line chart of University of Florida\\'s women\\'s applicant share from 2018 through 2022. A dashed horizontal line marks the school\\'s five-year average. Segments above the line have positive percentage-point labels and segments below it have negative labels.' width=672}\n:::\n:::\n\n\nThe blue and rust segments are not another model. They are the school-demeaned values in the table: positive when the year's share is above University of Florida's own mean and negative when it is below. The figure shows only the first subtraction. We remove year averages next.\n\nRead the 2018 row across. The observed share is 0.577; the school mean is 0.572; so `school_demeaned` is 0.005. That row's year mean is 0.524, and the grand mean is 0.530. After removing both the school and year averages, then adding the grand mean once, its `two_way_demeaned` value is 0.011.\n\nThe `school_demeaned` column removes University of Florida's usual level. That alone is useful, but national trends still remain. The average applicant share across every school rose to 0.539 in 2021. If every school moved because of a national change in college applications, we do not want to credit Florida's policy status for that shared movement.\n\nSo a two-way fixed-effect model also removes each year's average. Because this sample is perfectly balanced — the same 103 schools appear in all five years — the two-way arithmetic is especially transparent:\n\n$$\n\\widetilde{wshare}_{it}\n= wshare_{it}\n- \\overline{wshare}_{i}\n- \\overline{wshare}_{t}\n+ \\overline{wshare}.\n$$\n\nThe final `grand_mean` puts the overall level back once, so we do not subtract too much. For University of Florida in 2022, the calculation, shown to five decimal places so rounding does not get in the way, is:\n\n$$\n0.56186 - 0.57164 -\n0.53655 + 0.53026 =\n-0.01607.\n$$\n\nThat says its 2022 value was about 1.6 percentage points below what we would expect from its own typical level plus the common 2022 shift. The regression performs this operation for every school-year and, just as importantly, applies the same transformation to the event-study terms on the right-hand side.\n\n::: {.callout-note appearance=\"simple\" title=\"A Precision Note About De-meaning\"}\nThe arithmetic above is exact for this balanced, two-way example. Do not assume that every multi-fixed-effect model can be calculated by subtracting one mean after another. With an unbalanced panel or several non-nested fixed effects, the transformations overlap. `feols()` handles that projection for you.\n:::\n\nFixed effects remove time-invariant school differences and shocks common to every school in a year. They do **not** solve every omitted-variable problem. A state-specific change that occurs at the same time as anticipated *Dobbs* could still be a problem. That is why the pre-period estimates and the research design still matter.\n\n## The Main Model\n\nNow we can write the model that reproduces the main Walker event study.\n\n$$\n\\begin{aligned}\n\\text{wshare}_{ijt} ={}&\n\\mu_i + \\lambda_t \\\\\n&+ \\sum_{\\ell \\ne 2021}\n\\delta_\\ell \\left[\n\\text{repeal}_j \\times \\mathbb{1}(t = \\ell)\n\\right] + \\varepsilon_{ijt}.\n\\end{aligned}\n$$\n\nThe equation keeps the two independent fixed-effect baselines in view: $\\mu_i$ is each school's usual level, and $\\lambda_t$ is the shift shared by all schools in year $t$. The event-study terms, $\\delta_\\ell$, are still the terms we want to estimate. The legacy Walker code also includes a state term; the note immediately after the code explains why that does not add a third independent de-meaning step here.\n\nOnce the school's usual level has been absorbed, the same informal derivative has a particularly clean interpretation:\n\n$$\n\\left.\n\\frac{\\partial \\text{wshare}_{ijt}}\n{\\partial \\text{repeal}_j}\n\\right|_{t=\\ell}\n= \\delta_\\ell,\n\\qquad \\ell \\ne 2021.\n$$\n\nEach $\\delta_\\ell$ is the ban-minus-control change relative to 2021. The omitted 2021 interaction is zero by construction, not an estimated zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmain_model <- feols(\n  wshare ~ i(year, repeal, ref = 2021) | UNITID + STABBR + year,\n  cluster = ~STABBR,\n  data = df\n)\n\nsummary(main_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: wshare\nObservations: 515\nFixed-effects: UNITID: 103,  STABBR: 31,  year: 5\nStandard-errors: Clustered (STABBR) \n                   Estimate Std. Error   t value  Pr(>|t|)    \nyear::2018:repeal  0.000542   0.006427  0.084391 0.9333064    \nyear::2019:repeal  0.003257   0.004964  0.656192 0.5167024    \nyear::2020:repeal  0.000292   0.004490  0.065077 0.9485447    \nyear::2022:repeal -0.007223   0.002040 -3.541316 0.0013231 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 0.009029     Adj. R2: 0.983187\n                 Within R2: 0.026858\n```\n\n\n:::\n:::\n\n\n\n\nEverything before the vertical bar creates the event-study interactions. Everything after it is absorbed as fixed effects.\n\n- `UNITID` compares each school with itself over time.\n- `STABBR` is the legacy state fixed effect; it is nested within `UNITID` in this data.\n- `year` removes changes common to all schools in a given year.\n- `cluster = ~STABBR` allows the uncertainty to be correlated within a state. Schools in Texas can experience the same state-level shock; pretending they are completely independent would make our confidence intervals too narrow.\n\n::: {.callout-note appearance=\"simple\" title=\"Why Both School and State Appear in Walker's Formula\"}\nThis is not a contradiction. Every `UNITID` in this data belongs to exactly one `STABBR`. Once school fixed effects are included, state fixed effects do not create a third independent de-meaning step: the school effects already absorb them. A leaner `| UNITID + year` formula produces the same fitted values and event-study point estimates.\n\nIt does **not** necessarily print the same default clustered standard errors. `fixest`'s small-sample adjustment counts the absorbed fixed effects. Here, the 2022 clustered standard error is 0.0020 with the legacy formula and 0.0018 with the leaner one, even though the coefficient does not move. Keep the existing Walker formula when reproducing its reported output. In a new project, write the leaner formula if it reflects the design, then choose and report the standard-error correction deliberately. Keep state clustering either way.\n:::\n\nThe 2022 coefficient is -0.72 percentage points. Read it carefully: compared with the 2021 gap, women's share of applications fell by about 0.72 percentage points more at ban-state schools than at control-state schools in 2022. The 95% confidence interval does not cross zero. The 2018, 2019, and 2020 intervals do cross zero, which is reassuring for the parallel-trends story but does not prove it.\n\n### Read the Summary\n\n`summary(main_model)` reports more than the event-study estimates:\n\n- **Estimate** is the relative-to-2021 difference-in-difference for that year.\n- **Standard error**, **t value**, and **p value** describe how precisely the estimate is measured, using state-clustered uncertainty.\n- **Fixed-effects** counts tell you how many schools, states, and years were absorbed.\n- **Within R-squared** asks how much of the variation left after removing school and year baselines is associated with the event-study terms. It is a descriptive diagnostic, not a pass/fail grade for the model. The adjusted R-squared is high largely because each school has its own stable baseline.\n\nThere are only 31 state clusters, so do not let a small p value hypnotize you. The number tells you something useful; it does not relieve you of the job of judging the design.\n\n### Check It with `iplot()`\n\n`iplot()` makes a fast event-study graphic directly from the `i()` coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\niplot(main_model)\n```\n\n::: {.cell-output-display}\n![](walker-analysis_files/figure-html/demo-iplot-1.png){width=672}\n:::\n:::\n\n\nIt is great for a check. You should see the three pre-2021 estimates close to zero, the omitted 2021 reference period at zero, and the negative 2022 estimate. The 2021 dot is not an estimate that happened to equal zero; it is mechanically set to zero because `ref = 2021` made it the comparison year.\n\nDo not spend an hour styling `iplot()`. Its job is to tell you whether the model has produced the right basic result. The next chapter turns the model output into a dataframe and gives you a plot you can actually use in a README, paper, or presentation.\n\n## What's Next\n\nThe model object knows a lot, but it is not yet a useful figure. Next, we will pull the event-study estimates and confidence intervals into a plain dataframe, build a Walker-style plot, and turn the recurring steps into functions so a subgroup analysis is not a copy/paste disaster. We will then put the complete workflow in `scripts/analysis/main.R` and call it from `Run All.R`.\n",
    "supporting": [
      "walker-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}